imports:

- path: resources.jinja

resources:
- name: resources
  type: resources.jinja
  properties:
     SEND_GRID_API_KEY: <enter_your_send_grid_api_key_here>
     SEND_GRID_DOMAIN: <enter_domain_suffix_for_sending_email_notifications>
     BUCKET_NAME: <enter_bucket_name_for_images>
     REGION: europe-west1
